---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/19 11:31
---

---@type table<number, Framework.UI.Prefab>
prefabIDMap = {}
local contextID = 0
local function getPrefabID(prefab)
    contextID = contextID + 1
    prefabIDMap[contextID] = prefab
    return contextID
end

function getPrefabByID(contextID)
    return prefabIDMap[contextID]
end

function prefabComplete(contextID, go)
    prefab = prefabIDMap[contextID]
    if prefab then
        prefab:OnComplete(go)
    else
        LogUtil.LogError("can not find prefab by id:%s", contextID)
    end
end

--- prefab运行流程
--- 1.new一个prefab
--- 2.prefab通过cs接口加载资源
--- 3.加载完成之后，gameobject被放置到stage上指定的ui路径下，gameobject关联的DocumentClass链接Prefab(cs链接lua)，DocumentClass call Prefab:Init()
--- 4.Prefab在析构的时候，需要通知DocumentClass，
--- 5.gameobject在移除的时候，需要通过DocumentClass去调用Prefab:DestroyFromCS()



---@class Framework.UI.Prefab
---@field status number
Prefab = class("Framework.UI.Prefab")

function Prefab:ctor()
    self.status = 0
end

function Prefab:start()
    self:StartLogic()
end

function Prefab:LoadResource()
    self.status = 1
    local path = self:GetAssetPath()
    local contextID = self:getLoadContextID()
    Framework.core.CSBridge.LoadPrefab(path, contextID)
end

function Prefab:OnComplete(go)
    self.status = 2
end

function Prefab:StartLogic()
    error("must override!")
end

function Prefab:GetAssetPath()
    error("must override!")
end

function Prefab:Destroy()

end

function Prefab:DestroyFromCS()

end

function Prefab:getLoadContextID()
    return getPrefabID(self)
end

return Prefab