//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Framework_core_CSBridgeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(Framework.core.CSBridge), typeof(System.Object));
		L.RegFunction("LoadPrefab", LoadPrefab);
		L.RegFunction("New", _CreateFramework_core_CSBridge);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateFramework_core_CSBridge(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				Framework.core.CSBridge obj = new Framework.core.CSBridge();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: Framework.core.CSBridge.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadPrefab(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			string arg0 = ToLua.CheckString(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			Framework.core.CSBridge.LoadPrefab(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

